### ISSUE TITLE
Create solutions for codeforces solutions

### ISSUE THREAD

**Issue by js0805** [js0805/Codeforces-codechef-solutions#1]
One need to fork t of the repo and update their work on the forked one and then create a pull request. Mention your issue number on this issue itself. C++ solutions will be accepted. The solution must not already be present in the repo.
You can submit the solution by naming the file as Category(A,B...so on). (Question_Name).cpp or problem_number.cpp.
Anyone can work over it by submitting the PR.
Thank you!

**Comment by ksinha5nov** [comment]
Hi please assign this to me, Thank you.

**Comment by js0805** [comment]
@ksinha5nov go ahead select question which is not present in the repo and make pr and mention the pr number here.

**Comment by shrey27tri01** [comment]
Hey @js0805 ! Can you please review the pull request I created [here](https://github.com/js0805/Codeforces-codechef-solutions/pull/2) for issue #3 ?

**Comment by js0805** [comment]
> Hey @js0805 ! Can you please review the pull request I created [here](https://github.com/js0805/Codeforces-codechef-solutions/pull/2) for issue #3 ?

Verified!

**Comment by ksinha5nov** [comment]
@js0805 can you please look at the pr i created. Thank you.

**Comment by js0805** [comment]
> @js0805 can you please look at the pr i created. Thank you.

@ksinha5nov Verified!
